version: '3.7'

services:

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: db-pass-in
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=api-pass-in
      - POSTGRES_PASSWORD=api-pass-in
      - POSTGRES_DB=api-pass-in
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    networks:
      - passin 

  api-pass-in:
    build:
      context: .
    container_name: api-pass-in
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://api-pass-in:api-pass-in@postgres:5432/api-pass-in?schema=public
      - API_BASE_URL=http://localhost:3333 
    depends_on:
      - postgres 
    networks:
      - passin   

networks:
  passin:
    driver: bridge

volumes:
  postgres_data:
